# Fichier de configuration pour le développement
# Permet de tester l'application en local avant de mettre en production

services:

  # Base de données PostgreSQL
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
volumes:
  postgres_data:
