name: Build and deploy to prod

on:
  push:
    branches:
      - release
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata for backend
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend.Dockerfile
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          platforms: linux/amd64

      - name: Prepare metadata for frontend
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend.Dockerfile
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          platforms: linux/amd64
          secrets: |
            vite_api_url=${{ secrets.API_URL }}
            vite_google_maps_api_key=${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          build-args: |
            BUILDKIT_PROGRESS=plain
          provenance: false

      - name: Deploy the new images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker stack deploy -c stacks/prod/brestlife.yml brestlife_prod -d --with-registry-auth